<?php 
// reads previously posted values as for to prefillment* joy of the input fields
$customerInput = Mage::getSingleton("core/session")->getCustomerInput();
$customerInput = json_encode($customerInput);
$errorMessages = Mage::getSingleton("core/session")->getErrorMessage();
/*
$service = "http://ec2-54-246-38-175.eu-west-1.compute.amazonaws.com:3001/poi/premiumcategories";
$handle = curl_init();
curl_setopt($handle, CURLOPT_URL, $service);
curl_setopt($handle, CURLOPT_POST, false); 
curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
$categories = curl_exec($handle);
curl_close($handle);
$categories = trim($categories);
*/
// // // // 
$baseURL = Mage::getBaseUrl();
$skinURL = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$respPostURL = Mage::getBaseUrl() . "premium/index/pcfs_responsive";
// // // // 
$categories = '{
  "success": true,
  "data": [
    {
      "name": "Tierarzt",
      "key": "tierarzt",
      "image_map": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinDoctor.png",
      "image_map2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinDoctor%402x.png",
      "image_stream": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceDoctor.png",
      "image_stream2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceDoctor%402x.png",
      "image_comment": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIDoctor.png",
      "image_comment2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIDoctor%402x.png"
    },
    {
      "name": "Pension",
      "key": "pension",
      "image_map": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinHotel.png",
      "image_map2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinHotel%402x.png",
      "image_stream": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceHotel.png",
      "image_stream2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceHotel%402x.png",
      "image_comment": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIHotel.png",
      "image_comment2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIHotel%402x.png"
    },
    {
      "name": "Hundeschule",
      "key": "hundeschule",
      "image_map": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinSchool.png",
      "image_map2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinSchool%402x.png",
      "image_stream": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceSchool.png",
      "image_stream2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceSchool%402x.png",
      "image_comment": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOISchool.png",
      "image_comment2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOISchool%402x.png"
    },
    {
      "name": "Tierheilpraktiker",
      "key": "tierheilpraktiker",
      "image_map": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinHealth.png",
      "image_map2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinHealth%402x.png",
      "image_stream": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceHealth.png",
      "image_stream2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceHealth%402x.png",
      "image_comment": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIHealth.png",
      "image_comment2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIHealth%402x.png"
    },
    {
      "name": "Hundez&uuml;chter",
      "key": "hundezuechter",
      "image_map": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinZuechterTest.png",
      "image_map2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/specialPinZuechterTest%402x.png",
      "image_stream": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceZuechterTest.png",
      "image_stream2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/streamImageHeaderPremiumPlaceZuechterTest%402x.png",
      "image_comment": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIZuechterTest.png",
      "image_comment2x": "https://s3-eu-west-1.amazonaws.com/mygfiles/premium/profilePicturePOIZuechterTest%402x.png"
    }
  ],
  "itemCount": 5
}
';
$categories = json_decode($categories);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
<title></title>
<style type="text/css">

body {
	font-family: Arial, Helvetica;
}

#header {
	width: 834px;
	font-size: 24px;
	font-weight: bold;
	text-align: center;
	margin: 24px;
}

#menu {
	width: 1200px;
	text-align: center;
	margin: 24px;
}

#menu span{
	font-size: 18px;
	text-decoration: none;
	margin: 52px;
	color: white;
	font-weight: bold;
}

<?php

print <<<EOD

#menu .kontaktdaten{
	width: 370px;
	height: 46px;
	background-image: url({$skinURL}/frontend/default/mygassi/images/arrow_green.png);
	float: left;
	padding-top: 10px;
	background-repeat: no-repeat;
}

#menu .zahlungsdaten{
	width: 370px;
	height: 46px;
	background-image: url({$skinURL}/frontend/default/mygassi/images/arrow_yellow.png);
	float: left;
	padding-top: 10px;
	background-repeat: no-repeat;
}

#menu .abschluss{
	width: 370px;
	height: 46px;
	background-image: url({$skinURL}/frontend/default/mygassi/images/arrow_grey.png);
	float: left;
	padding-top: 10px;
	background-repeat: no-repeat;
}

EOD;

?>

#inputboxes {
	width: 834px;
	vertical-align: top;
	text-align: left;
}

#inputboxes ul li {
	list-style: none;
}

#premium_customer_form {
	width: 100%;
}

#personal_data_form {
	margin: 0px;
	width: 50%;
	float: left;
}

#corporate_data_form {
}

.liheader {
	font-size: 16px;
	font-weight: bold;	
}

.lisub {
	font-size: 10px;
}

.liplhldr {
	height: 200px;
}

#commando {
	font-size: 18px;
	margin: 52px;
	font-weight: bold;
	clear: both;
}

#error {
	width: 834px;
	border: 1px dotted red;
	padding: 32px;
}

a {
	text-decoration: none;
	color: #000000;
}

input[type="text"], input[type="submit"], select {	
	padding: 8px;
	width: 320px;
	font-size: 12px;
	margin-bottom: 8px;
}

input[type="text"] {
	color: #666666;
}

</style>

<script type="text/javascript" langauge="javascript" src="<?php print $baseURL . "js/jquery/jquery-2.0.0.min.js"?>"></script>
<script type="text/javascript" langauge="javascript">


jQuery(document).ready(function(){ CP.init(); });

CP = {
	deb: null,
	cur: null,
	corporateDataEqPersonalData: false,
	validFlags: [],
	isFormValid: false,
	cat: null,
	post: <?php print_r($customerInput); ?>,
	form: null,

	submitResponsive: function()
	{	
		jQuery.post("<?php print $respPostURL ?>", CP.form.serialize())
			.done(function(data){
				alert(data);
			});
	},
	
	out: function(message)
	{
		
	},

	setValidFlag: function(key)
	{
		CP.setOKBorder();	
		CP.validFlags[key] = true;
	},	

	setInvalidFlag: function(key)
	{
		CP.setErrBorder();
		CP.validFlags[key] = false;
	},
	
	init: function()
	{
		CP.deb = jQuery("#deb");
		CP.cat = jQuery("#cat");
		CP.form = jQuery("#premium_customer_form");	
		CP.btnSend = jQuery("#btnSend");

		jQuery("#inputboxes li input").bind("focus", function(e)
		{
			CP.putExistingInput();
			CP.validate();
		});

		jQuery("#inputboxes li input").bind("change", function(e)
		{
			CP.cur = jQuery(this);
			CP.cur.ghost = true;
			CP.setInputColor();
			CP.validate();
		});
		
		jQuery("#inputboxes li input").bind("click", function(e)
		{
			CP.putExistingInput();
			CP.cur = jQuery(this);
			CP.cur.ghost = false;
			CP.cutExistingInput();
			CP.setInputColor();
			CP.validate();
		});
		
		jQuery("#inputboxes li input").bind("keyup", function(e)
		{
			CP.cur = jQuery(this);
			CP.setInputColor();
			CP.validate();
		});

		jQuery("#inputboxes li select").bind("change", function(e)
		{
			CP.cur = jQuery(this);
			CP.validate();
		});
		
		jQuery("#inputboxes li select").bind("keyup", function(e)
		{
			CP.cur = jQuery(this);
			CP.validate();
		});

		jQuery("#is_personal_data").bind("click", function(e)
		{
			CP.cur = jQuery(this);
			if(CP.cur.is(":checked")){
				CP.copyPersonalDataToCorporateData();
				CP.corporateDataEqPersonalData = true;
			}
			else {
				CP.corporateDataEqPersonalData = false;
			}
		});
		
		CP.btnSend.attr("disabled", "disabled");
		CP.prefillForm();
	},

	/*
	initCategories: function()
	{
		if(null == CP.cat){ return false; }
		if(null == categories){ return false; }
		if(null == categories.data){ return false; }
		buff = '<option value="default_category">Bitte w&auml;hlen Sie eine Kategorie</option>';
		for(var idx in categories.data){
			keyy = categories.data[idx].key;
			name = categories.data[idx].name;
			buff +=	'<option value="'+keyy+'">'+name+'</option>';
		}
		CP.cat.html(buff);
		CP.cat.val("default_category");
	},
	*/
	
	cutExistingInput: function()
	{
		if(null == CP.cur){ 
			return; 
		}
		if("btnSend" == CP.cur.attr("id")){ 
			return; 
		}
		CP.cur.old = CP.cur.val();
		CP.cur.val("");
	},

	putExistingInput: function()
	{
		if(null == CP.cur){ 
			return; 
		} 
		if("btnSend" == CP.cur.attr("id")){ 
			return; 
		}
		if(false == CP.cur.ghost){
			CP.cur.val(CP.cur.old);
		}
	},
	
	prefillForm: function()
	{
		// returns without post
		if(null == CP.post){
			return;
		}
		// prefills input fields from previous post values
		jQuery("#inputboxes li input").each(function(index, value){
			key = jQuery(this).attr("name");
			if(undefined != key){
				val = jQuery(this).val();
				fil = CP.post[key] == "" ? val : CP.post[key];
				target = jQuery(this);
				target.val(fil);
				CP.cur = target;
				CP.validate();
			}
		});
		
		// pre selects category
		CP.cat.val(CP.post["cat"]);
	},

	copyPersonalDataToCorporateData: function()
	{
		// jQuery("#c_name").val(jQuery("#p_name").val());
		// jQuery("#c_name").change();
		jQuery("#c_zip").val(jQuery("#p_zip").val());
		jQuery("#c_zip").change();
		jQuery("#c_city").val(jQuery("#p_city").val());
		jQuery("#c_city").change();
		jQuery("#c_street").val(jQuery("#p_street").val());
		jQuery("#c_street").change();
		jQuery("#c_telephone").val(jQuery("#p_telephone").val());
		jQuery("#c_telephone").change();
	},

	enableCorporateDataInput: function()
	{
		jQuery("#c_street").removeAttr("disabled");
		jQuery("#c_zip").removeAttr("disabled");
		jQuery("#c_city").removeAttr("disabled");
		jQuery("#c_telephone").removeAttr("disabled");
	},

	disableCorporateDataInput: function()
	{
		jQuery("#c_street").attr("disabled", "disabled");
		jQuery("#c_zip").attr("disabled", "disabled");
		jQuery("#c_city").attr("disabled", "disabled");
		jQuery("#c_telephone").attr("disabled", "disabled");
	},

	setInputColor: function()
	{
		CP.cur.css("color", "#000000");
	},

	setErrBorder: function()
	{
		CP.cur.css("border-color", "#fb3c1a");
	},
	
	setOKBorder: function()
	{
		CP.cur.css("border-color", "#6aad1d");
	},

	validate: function()
	{
		if(null == CP.cur){
			return;
		}
		key = CP.cur.attr("name");
		val = CP.cur.val();
		switch(key){
			
			case "p_name":
				// p_name is string with a length of 8 chars
				if(8 > val.length){ 
					CP.setInvalidFlag("p_name");
				}
				else {
					CP.setValidFlag("p_name");
				}
				break;
			
			case "p_email":
				// email this is
				expr = new RegExp(/^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/);
				if(false == expr.test(val)){
					CP.setInvalidFlag("p_email");
				}
				else{
					CP.setValidFlag("p_email");
				}
				break;
			
			case "p_telephone":
				// telephone this is
				expr = new RegExp(/^\d+$/);
				strval = val;
				strval = strval.replace(new RegExp("\\(", "g"), "");
				strval = strval.replace(new RegExp("\\)", "g"), "");
				strval = strval.replace(new RegExp("\\/", "g"), "");
				strval = strval.replace(new RegExp("\\ ", "g"), "");
				strval = strval.replace(new RegExp("\\+", "g"), "");
				strval = strval.replace(new RegExp("\\-", "g"), "");
				strval = strval.replace(new RegExp("\\.", "g"), "");
				if(false == expr.test(strval) ||6 > strval.length){
					CP.setInvalidFlag("p_telephone");
				}
				else{
					CP.setValidFlag("p_telephone");
				}
				break;
			
			case "p_street":
				// length of 6? characters	
				if(6 > val.length){
					CP.setInvalidFlag("p_street");
				}
				else{
					CP.setValidFlag("p_street");
				}
				break;
			
			case "p_zip":
				// zip is digits 
				expr = new RegExp(/^\d+$/);
				if(false == expr.test(val) ||4 > val.length){
					CP.setInvalidFlag("p_zip");
				}
				else{
					CP.setValidFlag("p_zip");
				}
				break;

			case "p_city":
				// length of 2? characters
				if(2 > val.length){
					CP.setInvalidFlag("p_city");
				}
				else{
					CP.setValidFlag("p_city");
				}
				break;

			case "c_name":
				// c_name is string with a length of 8 chars
				if(8 > val.length){ 
					CP.setInvalidFlag("c_name");
				}
				else {
					CP.setValidFlag("c_name");
				}
				break;
			
			case "c_street":
				// length of 6? characters	
				if(6 > val.length){
					CP.setInvalidFlag("c_street");
				}
				else{
					CP.setValidFlag("c_street");
				}
				break;
	
			case "c_zip":
				// zip is digits 
				expr = new RegExp(/^\d+$/);
				if(false == expr.test(val) ||4 > val.length){
					CP.setInvalidFlag("c_zip");
				}
				else{
					CP.setValidFlag("c_zip");
				}
				break;
			
			case "c_city":
				// length of 2? characters
				if(2 > val.length){
					CP.setInvalidFlag("c_city");
				}
				else{
					CP.setValidFlag("c_city");
				}
				break;
		
			case "c_telephone":
				// telephone this is
				expr = new RegExp(/^\d+$/);
				strval = val;
				strval = strval.replace(new RegExp("\\(", "g"), "");
				strval = strval.replace(new RegExp("\\)", "g"), "");
				strval = strval.replace(new RegExp("\\/", "g"), "");
				strval = strval.replace(new RegExp("\\ ", "g"), "");
				strval = strval.replace(new RegExp("\\+", "g"), "");
				strval = strval.replace(new RegExp("\\-", "g"), "");
				strval = strval.replace(new RegExp("\\.", "g"), "");
				if(false == expr.test(strval) ||6 > strval.length){
					CP.setInvalidFlag("c_telephone");
				}
				else {
					CP.setValidFlag("c_telephone");
				}
				break;

			case "c_website":
				// length of 6? characters	
				if(6 > val.length){
					CP.setInvalidFlag("c_website");
				}
				else{
					CP.setValidFlag("c_website");
				}
				break;
		}

		// evaluates form is valid
		CP.isFormValid = true;
		i = Object.keys(CP.validFlags).length;
		if(12 > i){
		 	CP.isFormValid = false;
		}	
		else 
		{
			for(i in CP.validFlags){ 
				if(false == CP.validFlags[i]){
					CP.isFormValid = false;
				}
			}
		}

		// enabledisables :))) submit button
		if(CP.isFormValid){
			CP.btnSend.removeAttr("disabled");
		}
		else{
			CP.btnSend.attr("disabled", "disabled");
		}
	}
};

</script>

</head>

<body>

<center>

<?php 

if(null != $errorMessages){
	print <<<EOD
<div id="error">{$errorMessages}</div>

EOD;

}

$catOptions = "";
$sel = "selected";
foreach($categories->data as $cat){
	$catOptions .= '<option value="'.$cat->key.'" '.$sel.'>'.$cat->name.'</option>';
	$sel = "";
}

print <<<EOD

<div id="header"><span>Erstellen Sie in nur 3 Schritten Ihren MyGassi-Premiumort</span></div>

<div id="menu">
	<div class="kontaktdaten"><span>Kontaktdaten</span></div>
	<div class="zahlungsdaten"><span>Zahlungsdaten</span></div>
	<div class="abschluss"><span>Abschluss</span></div>
</div>

<div id="commando">Bitte eingeben Sie<sup>*</sup></div>

<div id="inputboxes">

	<form id="premium_customer_form" name="premium_customer_form" method="POST" action="{$baseURL}premium/index/pcfs">	
		
		<ul id="personal_data_form">
			<li class="liheader">Pers&ouml;hnliche Daten*</li>
			<li class="lisub">(werden in der App nicht angezeigt)</li>
			<li class="lisub">&nbsp;</li>
			<li><input type="text" id="p_name" name="p_name" value="Vor- und Nachname"></input></li>
			<li><input type="text" name="p_email" value="E-Mail-Adresse"></input></li>
			<li><input type="text" id="p_telephone" name="p_telephone" value="Telefonnummer"></input></li>
			<li><input type="text" id="p_street" name="p_street" value="Strasse"></input></li>
			<li><input type="text" id="p_zip" name="p_zip" value="Postleitzahl"></input></li>
			<li><input type="text" id="p_city" name="p_city" value="Stadt"></input></li>
			<input type="hidden" name="p_region_id" value="81"/>
			<input type="hidden" name="p_region" value="Hamburg"/>
			<li class="liplhldr">&nbsp;</li>
		</ul>
	
		<ul id="corporate_data_form">
			<li class="liheader">Unternehmensdaten*</li>
			<li class="lisub">&nbsp;</li>
			<li class="lisub">&nbsp;</li>
			<li><select id="cat" name="cat">{$catOptions}</select></li>
			<li><input type="text" id="c_name" name="c_name" value="Unternehmensname"></input></li>
			<li class="lisub">&nbsp;</li>
			<li class="lisub">&nbsp;</li>
			<li class="lisub">
				<input type="checkbox" id="is_personal_data" name="is_personal_data" value="is_personal_data"></input>
				<label for="is_personal_data">Entspricht den pers&ouml;nlichen Daten</label>
			</li>
			<li class="lisub">&nbsp;</li>
			<li><input type="text" id="c_street" name="c_street" value="Strasse"></input></li>
			<li><input type="text" id="c_zip" name="c_zip" value="Postleitzahl"></input></li>
			<li><input type="text" id="c_city" name="c_city" value="Stadt"></input></li>
			<li><input id="c_telephone" type="text" name="c_telephone" value="Telefonnummer"></input></li>
			<li><input type="text" name="c_website" value="Website"></input></li>
			<input type="hidden" name="c_region_id" value="81"/>
			<input type="hidden" name="c_region" value="Hamburg"/>
			<li><input id="btnSend" type="submit" value="Zahlungsdaten eingeben"></input></li>
		</ul>
	</form>
</div>

<!-- <textarea id="deb" style="width:750px; height:200px"></textarea> -->

</center>
</body>
</html>

EOD;
