<?php 
// $customerInput = Mage::getSingleton("core/session")->getCustomerInput();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<title></title>

<style type="text/css">

body {
	font-family: Arial, Helvetica;
}

#header {
	width: 834px;
	font-size: 24px;
	font-weight: bold;
	text-align: center;
	margin: 24px;
}

#menu, #commando_1, #commando_2 {
	width: 834px;
	text-align: center;
	margin: 24px;
}

#menu span {
	font-size: 18px;
	margin: 52px;
}

#commando_1, #commando_2 {
	font-size: 18px;
	margin: 52px;
	font-weight: bold;
}

#package_box_1 {
	width: 30%;
	border-style: solid;
	border-color: pink;
	text-align: left;
	float: left;
	margin-right: 24px; 
}

#package_box_1 ul li, #package_box_2 ul li, #package_box_3 ul li {
	margin-bottom: 24px;
	font-size: 14px;
}

#package_box_2 {
	width: 30%;
	border-style: solid;
	border-color: #cde012;
	text-align: left;
	float: left; 
	margin-right: 24px; 
}

#package_box_3 {
	width: 30%;
	border-style: solid;
	border-color: #ffcce0;
	text-align: left;
	float: left;
	margin-bottom: 32px;
}

#packages {
	width: 834px;
}

#commando_2 {
	width: 834px;
	clear: both;
}

#payment_method {
	width: 834px;
	text-align: left;
	font-size: 20px;
	font-weight: bold;
}

#payment_method form input {
	margin-bottom: 32px;
}

.sub {
	font-size: 10px;
}

.headline {
	font-size: 20px;
	font-weight: bold;
}

</style>

</head>

<body>

<center>

<?php 

if(null != $errorMessage){
	print <<<EOD
<div id="error">{$errorMessage}</div>

EOD;

}

?>

<form method="POST" action="<?php print Mage::getBaseUrl() . "premium/index/ptfs" ?>">

<div id="header"><span>Erstellen Sie in nur 3 Schritten Ihren MyGassi-Premiumort</span></div><!-- header -->

<div id="menu">
	<span class="">Kontaktdaten</span>
	<span class="">Zahlungsdaten</span>
	<span class="">Abschluss</span>
</div><!-- menu -->

<div id="commando_1">W&auml;hlen Sie Ihr gew&uuml;nschtes Premium-Paket aus<sup>*</sup></div><!-- commando_1 -->

<div id="packages">

<div id="package_box_1">
	<input type="radio" id="bronze" name="selected_package" value="bronze" checked>
		<label for="bronze"  class="headline">Paket "Bronze" €60 pro Jahr</label>
	</input>
	<br/>
	<span class="sub"><sup>*</sup>zzgl. 19% MwSt.</span>
	<ul class="package_description">
		<li>Ihr Unternehmen als f&uuml;r alle sichtbarer Pin auf der Karte</li>
		<li>M&ouml;glichkeiten zur direkten Kontaktaufnahme via E-Mail oder Telefon zu Ihrem Unternehmen</li>
		<li>Zugang zum MyGassi Adminportal zur selbst&auml;ndigen Pflege Ihrer Daten</li>
	</ul>
</div><!-- package_box_1 -->

<div id="package_box_2">
	<input type="radio" id="silver" name="selected_package" value="silver">
		<label for="silver" class="headline">Paket "Silber" €199 pro Jahr</label>
	</input>
	<br/>
	<span class="sub"><sup>*</sup>zzgl. 19% MwSt.</span>
	<ul class="package_description">
		<li>Ihr Unternehmen als f&uuml;r alle sichtbarer Pin auf der Karte</li>
		<li>M&ouml;glichkeiten zur direkten Kontaktaufnahme via E-Mail oder Telefon zu Ihrem Unternehmen</li>
		<li>Kommentarbox zur direkten Interaktion/Kommunikation mit den Nutzern der MyGassi App</li>
		<li>Zugang zum MyGassi Adminportal zur selbst&auml;ndigen Pflege Ihrer Daten</li>
	</ul>
</div><!-- package_box_2 -->

<div id="package_box_3">
	<input type="radio" id="gold" name="selected_package" value="gold">
		<label for="gold"  class="headline">Paket "Gold" €299 pro Jahr</label>
	</input>
	<br/>
	<span class="sub"><sup>*</sup>zzgl. 19% MwSt.</span>
	<ul class="package_description">
		<li>Ihr Unternehmen als f&uuml;r alle sichtbarer Pin auf der Karte</li>
		<li>M&ouml;glichkeiten zur direkten Kontaktaufnahme via E-Mail oder Telefon zu Ihrem Unternehmen</li>
		<li>Kommentarbox zur direkten Interaktion/Kommunikation mit den Nutzern der MyGassi App</li>
		<li>Anlegen von Ihren &Ouml;ffnungszeiten</li>
		<li>Anlegen von News, Tipps und Informationen sowie Aktionen und Gutschein mit Apple Passbookintegration</li>
		<li>Statistiken und Auswertungen von Klickzahlen und Nutzerverhalten</li>
		<li>Zugang zum MyGassi Adminportal zur selbst&auml;ndigen Pflege Ihrer Daten</li>
	</ul>	
</div><!-- package_box_3 -->

</div><!-- packages -->

<div id="commando_2">W&auml;hlen Sie Ihre gew&uuml;nschte Zahlungsweise bei j&auml;hrlicher Abrechnung aus<sup>*</sup></div><!-- commando_2 -->

<div id="payment_method">

		<p/>	
		<input type="radio" id="payment:checkmo" name="payment_type" value="checkmo">
			<label for="payment:checkmo">Scheck</label>
		</input>

		<p/>
		<input type="radio" id="payone_online_bank_transfer" name="payment_type" value="payone_online_bank_transfer">
			<label for="payone_online_bank_transfer">Sofort&uuml;berweisung</label>
		</input>
		
		<p/>
		<input type="radio" id="payone_wallet" name="payment_type" value="payone_wallet" checked>
			<label for="payone_wallet">PayPal</label>
		</input>

		<p/>	
		<input type="submit" value="Bestellung &uuml;berpr&uuml;fen"></input>
		<input type="hidden" name="payone_wallet_type" value="PPE"/>
		<input type="hidden" name="payone_config_payment_method_id" value="3"/>

</div><!-- payment_method -->

</form>

</body>

</html>

