<?php 
// reads previously posted values as for to prefill the input fields
// $post = Mage::getSingleton("core/session")->getPostValues();
// $post = json_encode($post);
$skinURL = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
<title></title>
<style type="text/css">

body {
	font-family: Arial, Helvetica;
}

#header {
	width: 834px;
	font-size: 24px;
	font-weight: bold;
	text-align: center;
	margin: 24px;
}


#menu {
	width: 1200px;
	text-align: center;
	margin: 24px;
}

#menu span {
	font-size: 18px;
	text-decoration: none;
	margin: 52px;
	color: white;
	font-weight: bold;
}

<?php

print <<<EOD

#menu .kontaktdaten{
	width: 370px;
	height: 46px;
	background-image: url({$skinURL}/frontend/default/mygassi/images/arrow_green.png);
	float: left;
}

#menu .zahlungsdaten{
	width: 370px;
	height: 46px;
	background-image: url({$skinURL}/frontend/default/mygassi/images/arrow_yellow.png);
	float: left;
}

#menu .abschluss{
	width: 370px;
	height: 46px;
	background-image: url({$skinURL}/frontend/default/mygassi/images/arrow_grey.png);
	float: left;
}

EOD;

?>

#commando {
	font-size: 18px;
	margin: 52px;
	font-weight: bold;
	clear: both;
}

</style>

</head>

<body>

<center>

<div id="header"><span>Erstellen Sie in nur 3 Schritten Ihren MyGassi-Premiumort</span></div>

<div id="menu">
	<span class="">Kontaktdaten</span>
	<span class="">Zahlungsdaten</span>
	<span class="">Abschluss</span>
</div>

<div id="commando">Danke!<sup>*</sup></div>

</center>
</body>
</html>
