<?php 
// reads previously posted values as for to prefill the input fields
// $post = Mage::getSingleton("core/session")->getPostValues();
// $post = json_encode($post);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
<title></title>
<style type="text/css">

body {
	font-family: Arial, Helvetica;
}

#header {
	width: 834px;
	font-size: 24px;
	font-weight: bold;
	text-align: center;
	margin: 24px;
}

#menu {
	width: 834px;
	text-align: center;
	margin: 24px;
}

#menu span {
	font-size: 18px;
	text-decoration: none;
	margin: 52px;
}

#commando {
	font-size: 18px;
	margin: 52px;
	font-weight: bold;
}

</style>

</head>

<body>

<center>

<div id="header"><span>Erstellen Sie in nur 3 Schritten Ihren MyGassi-Premiumort</span></div>

<div id="menu">
	<span class="">Kontaktdaten</span>
	<span class="">Zahlungsdaten</span>
	<span class="">Abschluss</span>
</div>

<div id="commando">Danke!<sup>*</sup></div>

</center>
</body>
</html>
