<?php 
// reads previously posted values as for to prefill the input fields
$customerInput = Mage::getSingleton("core/session")->getCustomerInput();
$paymentInput = Mage::getSingleton("core/session")->getPaymentInput();
// print_r($customerInput);
// print_r($paymentInput);
$baseURL = Mage::getBaseUrl();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<style type="text/css">

body {
	font-family: Arial, Helvetica;
}

a {
	text-decoration: none;
}

#header {
	width: 834px;
	font-size: 24px;
	font-weight: bold;
	text-align: center;
	margin: 24px;
}

#menu {
	width: 834px;
	text-align: center;
	margin: 24px;
}

#menu span {
	font-size: 18px;
	text-decoration: none;
	margin: 52px;
}

#commando {
	font-size: 18px;
	margin: 52px;
	font-weight: bold;
}

#output_1, #output_2 {
	width: 834px;
	text-align: left;
	margin-bottom: 32px;
}

#personal_data {
	text-align: left;
	float: left;
	height: 250px;
	width: 50%;
}

#corporate_data {
	height: 250px;
}

#personal_data span, #corporate_data span, #payment_method span {
	line-height: 32px;
}

#terms_and_conditions {
	width: 834px;
}

.headline {
	font-size: 24px;
	font-weight: bold;
}

</style>

<script type="text/javascript" langauge="javascript" src="<?php print Mage::getBaseUrl() . "js/jquery/jquery-2.0.0.min.js"?>"></script>
<script type="text/javascript" language="javascript">

jQuery(document).ready(function(){ CP.init(); });

CP = {
	btnSend: null,
	btnAccept: null,
	init: function(){
		CP.btnSend = jQuery("#submit");
		if(null != CP.btnSend){
			CP.btnSend.attr("disabled", "disabled");
		}
		CP.btnAccept = jQuery("#accept");
		if(null != CP.btnAccept){
			CP.btnAccept.bind("click", function(){
				if(CP.btnAccept.is(":checked")){
					CP.btnSend.removeAttr("disabled");
				}
				else {
					CP.btnSend.attr("disabled", "disabled");
				}
			});
		}
	}
}

</script>

</head>

<body>
<center>
<div id="header">Erstellen Sie in nur 3 Schritten Ihren MyGassi-Premiumort</div>
<div id="menu">
	<span class="">Kontaktdaten</span>
	<span class="">Zahlungsdaten</span>
	<span class="">Abschluss</span>
</div>

<div id="commando">Bitte &uuml;berpr&uuml;fen Sie Ihre eingegebenen Daten<sup>*</sup></div>

<div id="output_1">

<?php 

print <<<EOD
<div id="personal_data">
	<span class="headline">Pers&ouml;nliche Daten</span>
	<br/>
	<span class="message">{$customerInput["p_name"]}</span>
	<br/>
	<span class="message">{$customerInput["p_email"]}</span>
	<br/>
	<span class="message">{$customerInput["p_telephone"]}</span>
	<br/>
	<span class="message">{$customerInput["p_street"]}</span>
	<br/>
	<span class="message">{$customerInput["p_zip"]}</span>
	<br/>
	<sppan class="message">{$customerInput["p_city"]}</span>
</div><!-- personal_data -->

<div id="corporate_data">
	<span class="headline">Unternehmensdaten</span>
	<br/>
	<span class="message">{$customerInput["c_category"]}</span>
	<br/>
	<span class="message">{$customerInput["c_name"]}</span>
	<br/>
	<span class="message">{$customerInput["c_street"]}</span>
	<br/>
	<span class="message">{$customerInput["c_zip"]}</span>
	<br/>
	<span class="message">{$customerInput["c_city"]}</span>
	<br/>
	<span class="message">{$customerInput["c_telephone"]}</span>
</div><!-- corporate_data -->

</div><!-- ouput_1 -->

<div id="output_2">

<div id="payment_method">
	<span class="headline">Zahlungsdaten</span>	
	<br/>
	<span class="message">Gew&auml;hltes Paket: {$paymentInput["selected_package"]}</span>	
	<br/>
	<span class="message">{$paymentInput["selected_charge"]} pro Jahr</span>	
	<br/>
	<span class="message">Zahlung via: {$paymentInput["payment_type"]}</span>
</div><!-- payment_method -->

</div><!-- output_2 -->

<div id="terms_and_conditions">
	<form method="POST" action="{$baseURL}premium/index/place_order">
		<input type="checkbox" id="accept" name="accept" value="yes_i_do"></input>
		<label for="accept">Ich stimme den</label>
		<a href="http://apple.com/">Nutzungsbedingungen</a>
		der MyGassi GmbH f&uuml;r den Verkauf von Premiumorten zu.
		<p/>
		<input type="submit" id="submit" value="Bestellung absenden"></input>
	</form>
</div><!-- terms_and_conditions -->

EOD;

?>

</center>
</html>
</body>

