<div class="featured_bounds">
<div class="featured_product_title">MyGassi Top-Produkte</div>
<?php
$coll = Mage::getModel("catalog/product")
	->getCollection()
	->addAttributeToFilter("appears_on_the_internez", true)
	->load();

foreach($coll as $prod){
	$prod = $prod->load($prod->getId());
	// print_r($prod->debug());
	$name = $prod->getName();
	$description = $prod->getDescription();
	$price = Mage::helper("core")->currency($prod->getPrice());
	$src = "";
	foreach($prod->getMediaGalleryImages() as $image){
		$path = Mage::helper("catalog/image")->init($prod, "thumbnail", $image->getFile())->keepFrame(false)->resize(640);
		if("the1st" === $image->getLabel()){ 
			$src = (string)$path;
		}
	} 
	$prodURL = $prod->getUrlPath();
	$cartURL = Mage::helper("checkout/cart")->getAddUrl($prod);

	$pricesHTML = "";

	$uvp = Mage::helper("core")->currency($prod->getOldPrice());
	if(false == strpos($uvp, "0,00")){
		$pricesHTML .= '<font style="font-size: 10px; text-decoration: line-through">'.$uvp.'</font>';
		$pricesHTML .= '&nbsp;';
		$pricesHTML .= '&nbsp;';
		$pricesHTML .= '<font style="font-size: 18px;">'.$price.'</font>';
	}
	else{
		$pricesHTML .= '<font style="font-size: 18px;">'.$price.'</font>';
	}

	print <<<EOD
<div class="featured_product">
	<div class="featured_product_name"><a href="{$prodURL}">{$name}</a></div>
	<div class="featured_product_image"><div class="featured_product_border_a"><img class="featured_product_image_view" src="{$src}"/></div></div>
	<div class="featured_product_price"><div class="featured_product_border_b">{$pricesHTML}</div></div>
	<div class="featured_product_shipping"><div class="featured_product_border_c">Versandkostenfrei!</a></div></div>
	<div class="featured_product_closer"></div>
</div>
EOD;

}
?>
</div><!-- featured_bounds -->
<?php /**
<iframe width="100%" src="http://192.168.178.27/magento/checkout/cart/"></iframe>
<iframe width="100%" src="http://192.168.178.27/magento/checkout/onepage/"></iframe>
**/ ?>
